[package]
name = "fidelityfetch"
license = "MIT"
authors = ["Marc Beck König <mbkj@tutamail.com>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
exclude = [".github"]


[[bin]]
name = "fife"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
axum = "0.7.5"
mime_guess = "2.0.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
local-ip-address = "0.6.1"
mdns-sd = "0.11.1"
chrono = "0.4.38"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
