[package]
name = "fidelityfetch"
description = "Seamlessly setup a webserver to serve files recursively from a specified path"
license = "MIT"
authors = ["Marc Beck König <mbkj@tutamail.com>"]
version = "0.3.0"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/CramBL/fidelityfetch"
repository = "https://github.com/CramBL/fidelityfetch"
keywords = ["file-transfer", "command-line"]

exclude = [".github", "scripts"]

[[bin]]
name = "fife"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
clap_complete = "4.5.6"
axum = "0.7.5"
mime_guess = "2.0.5"
tokio = { version = "1.39", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
local-ip-address = "0.6.1"
mdns-sd = "0.11.1"
chrono = "0.4.38"
tokio-util = { version = "0.7.11", features = ["io"] }
tokio-stream = { version = "0.1.15", features = ["fs"] }
futures-util = "0.3.30"
percent-encoding = "2.3.1"

[dev-dependencies]
pretty_assertions = "1.4.0"
temp-dir = "0.1.11"
testresult = "0.4.0"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
