[dist.dependencies.apt]
# aarch64-unknown-linux-musl
gcc-aarch64-linux-gnu = { version = '11.2.0-1ubuntu1', targets = [
    "aarch64-unknown-linux-musl",
], stage = [
    "build",
] }
libc6-dev-i386 = { version = '2.35-0ubuntu3.8', targets = [
    "aarch64-unknown-linux-musl",
], stage = [
    "build",
] }
# armv7-unknown-linux-musleabihf && arm-unknown-linux-musleabihf
gcc-arm-linux-gnueabihf = { version = '11.2.0-1ubuntu1', targets = [
    "armv7-unknown-linux-musleabihf",
    "arm-unknown-linux-musleabihf",
], stage = [
    "build",
] }
