[env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"
CC_armv7-unknown-linux-musleabihf = "arm-linux-gnueabihf-gcc"
CC_arm-unknown-linux-musleabihf = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "arm-linux-gnueabihf-gcc"
