[env]
CC_aarch64_unknown_linux_musl = "aarch64-linux-gnu-gcc"
CC_armv7-unknown-linux-musleabihf = "arm-linux-gnueabihf-gcc"
CC_arm-unknown-linux-musleabihf = "arm-linux-gnueabihf-gcc"

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "link-self-contained=yes",
]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
