- name: Install AArch64 Toolchain
  run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-i386
- name: Install ARM Toolchain
  run: sudo apt-get update && sudo apt-get install gcc-arm-linux-gnueabihf
