- name: Install AArch64 Toolchain
  if: ${{ matrix.packages_install == 'aarch64-unknown-linux-musl' }}
  run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-i386
- name: Install ARM Toolchain
  if: ${{ matrix.packages_install == 'arm-unknown-linux-musleabihf' || matrix.packages_install == 'armv7-unknown-linux-musleabihf' }}
  run: sudo apt-get update && sudo apt-get install gcc-arm-linux-gnueabihf
