name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main, master ]

jobs:
  update-changelog:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: crambl/dependabot-changelog-writer@v0.5.0
      with:
        push_token: ${{ secrets.PAT_PUSH }}
