name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main, master ]

jobs:
  update-release-file:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: crambl/dependabot-changelog-writer@v0.1.0
